---
abstract: 'Generate page list HTML.'
author:
  - 'Michal Jurosz <mj@mj41.cz>'
  - 'Michal Špaček <skim@cpan.org>'
build_requires:
  Cwd: 0
  Data::Page: 0
  English: 0
  ExtUtils::MakeMaker: 6.36
  File::Spec: 0
  FindBin: 0
  Test::More: 0
  Test::Pod: 0
  Test::Pod::Coverage: 0
configure_requires:
  ExtUtils::MakeMaker: 6.36
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.06'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Data-Page-HTML
no_index:
  directory:
    - inc
    - t
requires:
  Exporter: 0
  Readonly: 0
resources:
  bugtracker: https://rt.cpan.org/Public/Dist/Display.html?Name=Data-Page-HTML
  homepage: https://github.com/tupinek/Data-Page-HTML
  license: http://dev.perl.org/licenses/
  repository: git://github.com/tupinek/Data-Page-HTML
version: 0.11
